### ISSUE TITLE
buffer.writeUInt64LE is undefined.

### ISSUE THREAD

**Issue by LuaTenshi** [scholtzm/node-steam-groups#2]
Currently getting the following error with this. (I assume both read and write are not defined.)

    ../node_modules/steam-groups/index.js:70
            buffer.writeUInt64LE(object.steamIdGroup || 0, 0);
                   ^
    TypeError: undefined is not a function

I have looked the error up and had no luck. The function is also not on the API page. https://nodejs.org/api/buffer.html

**Comment by scholtzm** [comment]
`writeUInt64LE` is part of `ref` which is no longer used in `node-steam` (since v0.6.8).

Basically said, this module is currently incompatible with the latest `node-steam`. I will update it as soon as possible.

**Comment by LuaTenshi** [comment]
Seems that they are now using... https://www.npmjs.com/package/bytebuffer

**Comment by scholtzm** [comment]
Yes, indeed. I will make the updates during the upcoming week.

**Comment by scholtzm** [comment]
@LuaTenshi check out the latest commit b6592186862f90876307169a58b61668869faa2c. I have done some brief testing and it should work fine now.

**Comment by LuaTenshi** [comment]
@scholtzm Yeah it works perfectly now!  :+1: :smile:

**Comment by scholtzm** [comment]
Good to know! I will update the npm package asap. Thanks for reporting.
