### ISSUE TITLE
Invite Steam Users to Group, do not work.

### ISSUE THREAD

**Issue by nicoasdd** [scholtzm/node-steam-groups#4]
im trying to invite all users of my page to the new SteamGroup. 
i have all the SIDs on my DB so i try to make a look where take all SID and send the group invite to each.. but it do not work, :/.
simply do not invite anyone, (i have 1184 users) is there an restriction on how many invites can send for hour? 
or simply i try to invite and other account (not in friends of the bot) and it do not sent the offer.

**Comment by scholtzm** [comment]
I believe there is a restriction for how many pending group invites you might have.

However, if you are unable to invite even a single person, there's most likely an issue in your code.

**Comment by tambu22** [comment]
in my code? i can invite 1 (if it is my friend).

**Comment by nicoasdd** [comment]
in my code? i can invite 1 (if it is my friend). (the ones who send the msg get the invite but noone else of the databerse.)
 steamFriends.on('friendMsg', function(user, message, type) {
    if(type === Steam.EChatEntryType.ChatMsg) 
    {
        steamGroups.inviteUserToGroup(steamGroupID64, user);
        connection.query("SELECT `sid` FROM `user`", function(err, row, fields)  
        {
            row.forEach(function (s) {
                steamGroups.inviteUserToGroup(steamGroupID64, s.sid);  
                console.log('invited '+ s.sid); 
            });  
            console.log('done');
        });
    }
});

this is my code. (Tnks for fast help :dancer: )

**Comment by nicoasdd** [comment]
i check group history and sended 200 invites, so i ll close the issue. tnks for fast response.

**Comment by scholtzm** [comment]
200? In that case it looks like there is:
- no limit for pending invites
- no limit regarding relationship state

Good to know. However, I would be very careful when inviting such a large amount of people.

**Comment by nicoasdd** [comment]
yes there ir limit! i try to invite 1200 and only sent to 200..
bro why ur code dont give a callback with the state?

**Comment by scholtzm** [comment]
There is no callback because there is no response from Steam whether the attempt was successful or not.

Just like with [`sendMessage` and other methods](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#methods) in node-steam.

**Comment by nicoasdd** [comment]
okay :/ i think thac u can add it. like when u send it manually "offer was sente" or the offer wasnt sent because alredy invite.

ty for fast reply :) cya and GL

**Comment by scholtzm** [comment]
node-steam-groups doesn't use the WebAPI, so there is no response.
