### ISSUE TITLE
Remove user from group

### ISSUE THREAD

**Issue by fluxX04** [scholtzm/node-steam-groups#5]
Hi,

would it be possible to make a function to remove an user from a group?

Thanks.

**Comment by scholtzm** [comment]
This can be only done using Steam's HTTP API, in which case you can use [this](https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamGroup#kicksteamid-callback).

**Comment by fluxX04** [comment]
Alright, Thanks for the heads-up!
