### ISSUE TITLE
do not work with  Steam 1.4.0

### ISSUE THREAD

**Issue by Dead-Master** [scholtzm/node-steam-groups#6]
help :)

**Comment by scholtzm** [comment]
It does work just fine.

Can you provide more info?

**Comment by Dead-Master** [comment]
var fs = require('fs');
var crypto = require('crypto');
var config  = require('./config.js');
var Steam = require('steam');
var SteamGroups = require('steam-groups');
var SteamTotp = require('steam-totp');

var logOnOptions = {
    account_name: config.bot.username,
    password: config.bot.password,
    two_factor_code: SteamTotp.generateAuthCode(config.sharedKey)
};

logOnOptions.sha_sentryfile = getSHA1(fs.readFileSync(config.sentry));

function getSHA1(bytes) {
    var shasum = crypto.createHash('sha1');
    shasum.end(bytes);
    return shasum.read();
}

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
var steamGroups = new SteamGroups(steamClient);

var groupID = '*****';

function steamBotLogger(log){
    console.log(log);
}

steamClient.connect();
steamClient.on('debug', steamBotLogger);
steamClient.on('connected', function() {
    steamUser.logOn(logOnOptions);
});

steamClient.on('logOnResponse', function(logonResp) {
    if (logonResp.eresult === Steam.EResult.OK) {
        steamBotLogger('Logged in!');
        steamFriends.setPersonaState(Steam.EPersonaState.Online);
    }
});

steamClient.on('servers', function(servers) {
    fs.writeFile('servers', JSON.stringify(servers));
});

steamUser.on('updateMachineAuth', function(sentry, callback) {
    console('updateMachineAuth');
    fs.writeFileSync('sentry', sentry.bytes);
    callback({ sha_file: getSHA1(sentry.bytes) });
});

steamFriends.on('friendMsg', function(user, message, type) {
    if(type === Steam.EChatEntryType.ChatMsg) {
        steamGroups.inviteUserToGroup(groupID, user);
        steamFriends.sendMessage(user, 'invite to group ' + groupID);
    }
});

**Comment by Dead-Master** [comment]
bot admin group
if i say - hi say to me "invite to group ХХХ", bat invite I not see
if use web interface - invite go to me

sorry my english

or i have error in code?

update code in post

**Comment by scholtzm** [comment]
Is the groupID in correct format?

btw. bot does not have to be group admin.

Also, the invite can be sent only once if you decline it. To allow the bot to send the invite again, you need to join the group and then leave it. This will allow the bot to send you an invite once again.

**Comment by Dead-Master** [comment]
Thank you very much, i use incorrect ID format
Thank you very much

**Comment by scholtzm** [comment]
Glad you got it fixed.
