### ISSUE TITLE
Sending Group Invites

### ISSUE THREAD

**Issue by Exokay** [scholtzm/node-steam-groups#7]
Good morning everyone,

I made a small bot to enhance the size of our group.
My problem is,
If I use the steamGroups.inviteUserToGroup() function, it will invite a single person when I set the info for 1 player.
(i haven't invited 200 ppl yet.)

So i then started adding ' to the front and end of the SteamID-variable. This made me not crashing anymore but it wont invite.

steamGroups.inviteUserToGroup('doesntcarehere','76561198013129088'); <- works
steamGroups.inviteUserToGroup('doesntcarehere',inviteid); <- does nothing.
output inviteid -> '76561198013129088'

if i use the inviteid variable with having no ' at the end/beginning let's me crash the bot.
error 'TypeError: str.indexOf is not a function'

**Comment by Exokay** [comment]
nvm fixed it.

**Comment by scholtzm** [comment]
All IDs need to be treated as strings (just like `node-steam` does).
