### ISSUE TITLE
Cant get this working

### ISSUE THREAD

**Issue by TheRealKev1n** [scholtzm/node-steam-groups#8]
Hello, 

I have tried an other script so invite user to my group but it doesnt work i got it working so i can login to steam with node js and respond too chat messages but i cant get it working to send a invite to my group to a certain user. 

It keeps saying that some functions doesnt exists.

Does someone have a full example for me (login to steam + send invite to group) so i can play around with it im new to node js so it would be nice.
i installed this already:
- npm install steam@1.4.0
- npm install steam-groups

Thanks, 
Kevin

**Comment by scholtzm** [comment]
If you could provide basic script (of what you have so far), I could probably fix it for you.

**Comment by TheRealKev1n** [comment]
@scholtzm Here is the script i have now, as i said im new to this so dont expect much

`
var logOnOptions = {
    accountName: 'xxxx',
    password: 'xxxx'
};

var authCode = 'xxx'; // code received by email

if (require('fs').existsSync('sentry')) {
    logOnOptions['shaSentryfile'] = require('fs').readFileSync('sentry');
} else if (authCode != '') {
    logOnOptions['authCode'] = authCode;
}

var Steam = require('steam');
var SteamGroups = require('steam-groups');

// Create new SteamClient object and pass it as a constructor param
var client = new Steam.SteamClient();
var steamFriends = new Steam.SteamFriends(client);

var steamGroups = new SteamGroups(client);

// Connect to Steam network and add additional code here ...

client.on('loggedOn', function(result) {
    client.setPersonaName('TBOT');
    client.setPersonaState(Steam.EPersonaState.Online);
    console.log('Logged in!');
    client.gamesPlayed([730]);
});

client.on('webSessionID', function(sessionID) {
    client.webLogOn(function(newCookie){
        offers.setup({
            sessionID: sessionID,
            webCookie: newCookie
        });
    });
});

// Decline any incoming group invite
steamFriends.on('group', function(group, relationship) {
    if(relationship === Steam.EClanRelationship.Invited) {
        steamGroups.acknowledgeGroupInvite(group, false);
    }
});

// Invite anyone who messages us to a group
steamFriends.on('friendMsg', function(user, message, type) {
    if(type === Steam.EChatEntryType.ChatMsg) {
        steamGroups.inviteUserToGroup('1234567890', user);
    }
});

` 

The error im getting when i do node bot.js (this file) is:

`TypeError: Steam.SteamFriends is not a constructor
    at Object.<anonymous> (/var/www/vhosts/domain/httpdocs/*js:19:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
`

**Comment by TheRealKev1n** [comment]
First i need to get to login it worked before i added steam-groups

**Comment by scholtzm** [comment]
Well, you are mixing code from old `node-steam` API with some new code. This won't work and I see several issues in your script.

This is an _issue tracker_ so your question doesn't fit here. I'd suggest asking in one of the [discussion boards.](https://github.com/scholtzm/awesome-steam#discussion-boards)
